#! /bin/bash
#
# run ./configure --help   for available options

. .scripts/platform_functions
lcgplatform=$(check_platform)

./configure --lcgplatform=${lcgplatform} --with-clhepversion=1.9.3.1 

exit

