{
TFile *myFile = new TFile("dstarpi.root","READ");
myFile->ls();

TCanvas *myCanvas = new TCanvas("c","dstarpi",0,0,600,600);
myCanvas->Divide(2,3);

TH1F *th1=h1;
TH1F *th2=h2;
TH1F *th3=h3;
TH1F *th4=h4;
TH1F *th5=h5;

TH1F* sum=new TH1F(*h2+*h5);
TH1F* diff=new TH1F(*h2-*h5);
TH1F* asym=new TH1F((*diff)/(*sum));

TH1F* suma=new TH1F(*h3+*h4);
TH1F* diffa=new TH1F(*h3-*h4);
TH1F* asyma=new TH1F((*diffa)/(*suma));




myCanvas->cd(1);
th2->Draw();
th5->Draw("SAME");
myCanvas.Update();

myCanvas->cd(2);
th3->Draw();
th4->Draw("SAME");
myCanvas.Update();

myCanvas->cd(3);
th4->Draw();
myCanvas.Update();

myCanvas->cd(4);
th5->Draw();
myCanvas.Update();

myCanvas->cd(5);
asym->Draw();
myCanvas.Update();

myCanvas->cd(6);
asyma->Draw();
myCanvas.Update();


myCanvas->Print("ssdcp.eps");



}

