{
TFile *myFile = new TFile("jpsipolar.root","READ");
myFile->ls();
TCanvas *myCanvas = new TCanvas("c","JPSIPOLAR",0,0,400,600);
myCanvas->Divide(1,3);
myCanvas->cd(1);
  
TH1F *hist1=h1;
TH1F *hist2=h2;
TH1F *hist3=h3;

TF1 *f1=new TF1("f1", "[0]*(1.0 + [1]*x*x)",-1.0,1.0); 
f1->SetParameters(1,0);
hist1->Fit("f1");
myCanvas->cd(2);
hist2->Fit("f1");
myCanvas->cd(3);
hist3->Fit("f1");

myCanvas.Update();

myCanvas->Print("jpsipolar.eps");

}
