{
TFile *myFile = new TFile("kstarll.root","READ");
myFile->ls();
TCanvas *myCanvas = new TCanvas("c","KSTARLL",0,0,600,400);
myCanvas->Divide(2,2);
myCanvas->cd(1);

TH2F *hist1=h1;
TH1F *hist2=h2;

TH1F *hist7=h7;
TH1F *hist8=h8;

hist1->Draw();
myCanvas.Update();
myCanvas->cd(2);
hist2->Draw();
myCanvas.Update();

myCanvas->cd(3);
hist7->Draw();
myCanvas.Update();

myCanvas->cd(4);
hist8->Draw();
myCanvas.Update();


myCanvas->Print("kstarll.eps");

}
