{
TFile *myFile = new TFile("test2.root","READ");
myFile->ls();
TCanvas *myCanvas = new TCanvas("c","TEST2",0,0,600,400);
myCanvas->Divide(2,2);
myCanvas->cd(1);

TH1F *hist3=h3;
TH1F *hist4=h4;
TH1F *hist30=h30;
TH1F *hist31=h31;

hist3->Draw();
myCanvas.Update();
myCanvas->cd(2);
hist4->Draw();
myCanvas.Update();
myCanvas->cd(3);
hist30->Draw("BOX");
myCanvas.Update();
myCanvas->cd(4);
hist31->Draw("BOX");
myCanvas.Update();

myCanvas->Print("test2.eps");



}
