./compareRootFiles "tauolaDecay1" "rootFiles/tauolaDecay1.root" "rootFiles/tauolaDecay1.root" "#tau^{-} #rightarrow e^{-} #nu_{#tau} #bar{#nu_{e}}"
./compareRootFiles "tauolaDecay2" "rootFiles/tauolaDecay2.root" "rootFiles/tauolaDecay2.root" "#tau^{-} #rightarrow #mu^{-} #nu_{#tau} #bar{#nu_{#mu}}"
./compareRootFiles "tauolaDecay3" "rootFiles/tauolaDecay3.root" "rootFiles/tauolaDecay3.root" "#tau^{-} #rightarrow #pi^{-} #nu_{#tau}"
./compareRootFiles "tauolaDecay4" "rootFiles/tauolaDecay4.root" "rootFiles/tauolaDecay4.root" "#tau^{-} #rightarrow #rho^{-} #nu_{#tau}"
./compareRootFiles "tauolaDecay5" "rootFiles/tauolaDecay5.root" "rootFiles/tauolaDecay5.root" "#tau^{-} #rightarrow a_{1}^{-} #nu_{#tau}"
./compareRootFiles "tauolaDecay6" "rootFiles/tauolaDecay6.root" "rootFiles/tauolaDecay6.root" "#tau^{-} #rightarrow K^{-} #nu_{#tau}"
./compareRootFiles "tauolaDecay7" "rootFiles/tauolaDecay7.root" "rootFiles/tauolaDecay7.root" "#tau^{-} #rightarrow K^{*-} #nu_{#tau}"
./compareRootFiles "tauolaDecay8" "rootFiles/tauolaDecay8.root" "rootFiles/tauolaDecay8.root" "#tau^{-} #rightarrow 2#pi^{-} #pi^{+} #pi^{0} #nu_{#tau}"
./compareRootFiles "tauolaDecay9" "rootFiles/tauolaDecay9.root" "rootFiles/tauolaDecay9.root" "#tau^{-} #rightarrow 3#pi^{0} #pi^{-} #nu_{#tau}"
./compareRootFiles "tauolaDecay10" "rootFiles/tauolaDecay10.root" "rootFiles/tauolaDecay10.root" "#tau^{-} #rightarrow 2#pi^{-} #pi^{+} 2#pi^{0} #nu_{#tau}"
./compareRootFiles "tauolaDecay11" "rootFiles/tauolaDecay11.root" "rootFiles/tauolaDecay11.root" "#tau^{-} #rightarrow 3#pi^{-} 2#pi^{+} #nu_{#tau}"
./compareRootFiles "tauolaDecay12" "rootFiles/tauolaDecay12.root" "rootFiles/tauolaDecay12.root" "#tau^{-} #rightarrow 3#pi^{-} 2#pi^{+} #pi^{0} #nu_{#tau}"
./compareRootFiles "tauolaDecay13" "rootFiles/tauolaDecay13.root" "rootFiles/tauolaDecay13.root" "#tau^{-} #rightarrow 2#pi^{-} #pi^{+} 3#pi^{0} #nu_{#tau}"
./compareRootFiles "tauolaDecay14" "rootFiles/tauolaDecay14.root" "rootFiles/tauolaDecay14.root" "#tau^{-} #rightarrow K^{-} K^{+} #pi^{-} #nu_{#tau}"
./compareRootFiles "tauolaDecay15" "rootFiles/tauolaDecay15.root" "rootFiles/tauolaDecay15.root" "#tau^{-} #rightarrow #bar{K^{0}} K^{0} #pi^{-} #nu_{#tau}"
./compareRootFiles "tauolaDecay16" "rootFiles/tauolaDecay16.root" "rootFiles/tauolaDecay16.root" "#tau^{-} #rightarrow K^{-} #bar{K^{0}} #pi^{0} #nu_{#tau}"
./compareRootFiles "tauolaDecay17" "rootFiles/tauolaDecay17.root" "rootFiles/tauolaDecay17.root" "#tau^{-} #rightarrow 2#pi^{0} K^{-} #nu_{#tau}"
./compareRootFiles "tauolaDecay18" "rootFiles/tauolaDecay18.root" "rootFiles/tauolaDecay18.root" "#tau^{-} #rightarrow #pi^{-} #pi^{+} K^{-} #nu_{#tau}"
./compareRootFiles "tauolaDecay19" "rootFiles/tauolaDecay19.root" "rootFiles/tauolaDecay19.root" "#tau^{-} #rightarrow #pi^{-} #pi^{0} K^{0} #nu_{#tau}"
./compareRootFiles "tauolaDecay20" "rootFiles/tauolaDecay20.root" "rootFiles/tauolaDecay20.root" "#tau^{-} #rightarrow #eta #pi^{-} #pi^{0} #nu_{#tau}"
./compareRootFiles "tauolaDecay21" "rootFiles/tauolaDecay21.root" "rootFiles/tauolaDecay21.root" "#tau^{-} #rightarrow #pi^{-} #pi^{0} #gamma #nu_{#tau}"
./compareRootFiles "tauolaDecay22" "rootFiles/tauolaDecay22.root" "rootFiles/tauolaDecay22.root" "#tau^{-} #rightarrow K^{-} #bar{K^{0}} #nu_{#tau}"
