./compareRootFiles "tauPythiaDecay1" "rootFiles/tauPythiaDecay1.root" "rootFiles/tauPythiaDecay1.root" "#tau^{-} #rightarrow #nu_{#tau} #gamma #pi^{-} #pi^{0}"
./compareRootFiles "tauPythiaDecay2" "rootFiles/tauPythiaDecay2.root" "rootFiles/tauPythiaDecay2.root" "#tau^{-} #rightarrow #nu_{#tau} K^{-} #pi^{0} #pi^{0}"
./compareRootFiles "tauPythiaDecay3" "rootFiles/tauPythiaDecay3.root" "rootFiles/tauPythiaDecay3.root" "#tau^{-} #rightarrow #nu_{#tau} #pi^{-} #pi^{0} #pi^{0} #pi^{0}"
./compareRootFiles "tauPythiaDecay4" "rootFiles/tauPythiaDecay4.root" "rootFiles/tauPythiaDecay4.root" "#tau^{-} #rightarrow #nu_{#tau} #pi^{-} #bar{K^{0}}"
./compareRootFiles "tauPythiaDecay5" "rootFiles/tauPythiaDecay5.root" "rootFiles/tauPythiaDecay5.root" "#tau^{-} #rightarrow #nu_{#tau} K^{-} K^{0}"
./compareRootFiles "tauPythiaDecay6" "rootFiles/tauPythiaDecay6.root" "rootFiles/tauPythiaDecay6.root" "#tau^{-} #rightarrow #nu_{#tau} K^{0} #pi^{-} #bar{K^{0}}"
./compareRootFiles "tauPythiaDecay7" "rootFiles/tauPythiaDecay7.root" "rootFiles/tauPythiaDecay7.root" "#tau^{-} #rightarrow #nu_{#tau} K^{-} #pi^{0} #pi^{0}"
./compareRootFiles "tauPythiaDecay8" "rootFiles/tauPythiaDecay8.root" "rootFiles/tauPythiaDecay8.root" "#tau^{-} #rightarrow #nu_{#tau} #pi^{-} #bar{K^{0}} #pi^{0}"
./compareRootFiles "tauPythiaDecay9" "rootFiles/tauPythiaDecay9.root" "rootFiles/tauPythiaDecay9.root" "#tau^{-} #rightarrow #nu_{#tau} #pi^{-} #pi^{+} #pi^{-} #pi^{0}"
./compareRootFiles "tauPythiaDecay10" "rootFiles/tauPythiaDecay10.root" "rootFiles/tauPythiaDecay10.root" "#tau^{-} #rightarrow #nu_{#tau} K^{-} #pi^{+} #pi^{-}"
./compareRootFiles "tauPythiaDecay11" "rootFiles/tauPythiaDecay11.root" "rootFiles/tauPythiaDecay11.root" "#tau^{-} #rightarrow #nu_{#tau} K^{-} #pi^{+} #pi^{-} #pi^{0}"
./compareRootFiles "tauPythiaDecay12" "rootFiles/tauPythiaDecay12.root" "rootFiles/tauPythiaDecay12.root" "#tau^{-} #rightarrow #nu_{#tau} K^{-} #pi^{-} K^{+}"
./compareRootFiles "tauPythiaDecay13" "rootFiles/tauPythiaDecay13.root" "rootFiles/tauPythiaDecay13.root" "#tau^{-} #rightarrow #nu_{#tau} K^{-} K^{+} K^{-}"
./compareRootFiles "tauPythiaDecay14" "rootFiles/tauPythiaDecay14.root" "rootFiles/tauPythiaDecay14.root" "#tau^{-} #rightarrow #nu_{#tau} #eta #pi^{-} #pi^{0}"
./compareRootFiles "tauPythiaDecay15" "rootFiles/tauPythiaDecay15.root" "rootFiles/tauPythiaDecay15.root" "#tau^{-} #rightarrow #nu_{#tau} #pi^{-} #omega #pi^{0}"
./compareRootFiles "tauPythiaDecay16" "rootFiles/tauPythiaDecay16.root" "rootFiles/tauPythiaDecay16.root" "#tau^{-} #rightarrow #nu_{#tau} K^{-} #omega"
