./compareRootFiles "Bs0PythiaDecay1" "rootFiles/Bs0PythiaDecay1.root" "rootFiles/Bs0PythiaDecay1.root" "B^{0}_{s} #rightarrow #bar{cs}_{0} ud_{0}"
./compareRootFiles "Bs0PythiaDecay2" "rootFiles/Bs0PythiaDecay2.root" "rootFiles/Bs0PythiaDecay2.root" "B^{0}_{s} #rightarrow #bar{cs}_{1} ud_{1}"
./compareRootFiles "Bs0PythiaDecay3" "rootFiles/Bs0PythiaDecay3.root" "rootFiles/Bs0PythiaDecay3.root" "B^{0}_{s} #rightarrow u #bar{d} #bar{c} s (weak)"
./compareRootFiles "Bs0PythiaDecay4" "rootFiles/Bs0PythiaDecay4.root" "rootFiles/Bs0PythiaDecay4.root" "B^{0}_{s} #rightarrow u #bar{d} #bar{c} s"
./compareRootFiles "Bs0PythiaDecay5" "rootFiles/Bs0PythiaDecay5.root" "rootFiles/Bs0PythiaDecay5.root" "B^{0}_{s} #rightarrow u #bar{c} #bar{d} s (weak)"
./compareRootFiles "Bs0PythiaDecay6" "rootFiles/Bs0PythiaDecay6.root" "rootFiles/Bs0PythiaDecay6.root" "B^{0}_{s} #rightarrow c #bar{s} #bar{u} s (weak)"
./compareRootFiles "Bs0PythiaDecay7" "rootFiles/Bs0PythiaDecay7.root" "rootFiles/Bs0PythiaDecay7.root" "B^{0}_{s} #rightarrow u #bar{s} #bar{c} s (weak)"
./compareRootFiles "Bs0PythiaDecay8" "rootFiles/Bs0PythiaDecay8.root" "rootFiles/Bs0PythiaDecay8.root" "B^{0}_{s} #rightarrow u #bar{s} #bar{c} s"
./compareRootFiles "Bs0PythiaDecay9" "rootFiles/Bs0PythiaDecay9.root" "rootFiles/Bs0PythiaDecay9.root" "B^{0}_{s} #rightarrow u #bar{c} #bar{s} s (weak)"
./compareRootFiles "Bs0PythiaDecay10" "rootFiles/Bs0PythiaDecay10.root" "rootFiles/Bs0PythiaDecay10.root" "B^{0}_{s} #rightarrow c #bar{d} #bar{c} s"
./compareRootFiles "Bs0PythiaDecay11" "rootFiles/Bs0PythiaDecay11.root" "rootFiles/Bs0PythiaDecay11.root" "B^{0}_{s} #rightarrow c #bar{d} #bar{c} s"
./compareRootFiles "Bs0PythiaDecay12" "rootFiles/Bs0PythiaDecay12.root" "rootFiles/Bs0PythiaDecay12.root" "B^{0}_{s} #rightarrow u #bar{u} #bar{d} s (weak)"
./compareRootFiles "Bs0PythiaDecay13" "rootFiles/Bs0PythiaDecay13.root" "rootFiles/Bs0PythiaDecay13.root" "B^{0}_{s} #rightarrow d #bar{d} #bar{d} s (weak)"
./compareRootFiles "Bs0PythiaDecay14" "rootFiles/Bs0PythiaDecay14.root" "rootFiles/Bs0PythiaDecay14.root" "B^{0}_{s} #rightarrow s #bar{s} #bar{d} s (weak)"
./compareRootFiles "Bs0PythiaDecay15" "rootFiles/Bs0PythiaDecay15.root" "rootFiles/Bs0PythiaDecay15.root" "B^{0}_{s} #rightarrow u #bar{u} #bar{s} s (weak)"
./compareRootFiles "Bs0PythiaDecay16" "rootFiles/Bs0PythiaDecay16.root" "rootFiles/Bs0PythiaDecay16.root" "B^{0}_{s} #rightarrow d #bar{d} #bar{s} s (weak)"
./compareRootFiles "Bs0PythiaDecay17" "rootFiles/Bs0PythiaDecay17.root" "rootFiles/Bs0PythiaDecay17.root" "B^{0}_{s} #rightarrow s #bar{s} #bar{s} s (weak)"
./compareRootFiles "Bs0PythiaDecay18" "rootFiles/Bs0PythiaDecay18.root" "rootFiles/Bs0PythiaDecay18.root" "B^{0}_{s} #rightarrow #bar{s} s"
