./compareRootFiles "BpPythiaDecay1" "rootFiles/BpPythiaDecay1.root" "rootFiles/BpPythiaDecay1.root" "B^{+} #rightarrow #bar{cd}_{1} uu_{1}"
./compareRootFiles "BpPythiaDecay2" "rootFiles/BpPythiaDecay2.root" "rootFiles/BpPythiaDecay2.root" "B^{+} #rightarrow u #bar{d} #bar{c} u (weak)"
./compareRootFiles "BpPythiaDecay3" "rootFiles/BpPythiaDecay3.root" "rootFiles/BpPythiaDecay3.root" "B^{+} #rightarrow u #bar{d} #bar{c} u"
./compareRootFiles "BpPythiaDecay4" "rootFiles/BpPythiaDecay4.root" "rootFiles/BpPythiaDecay4.root" "B^{+} #rightarrow u #bar{s} #bar{c} u"
./compareRootFiles "BpPythiaDecay5" "rootFiles/BpPythiaDecay5.root" "rootFiles/BpPythiaDecay5.root" "B^{+} #rightarrow c #bar{s} #bar{c} u"
./compareRootFiles "BpPythiaDecay6" "rootFiles/BpPythiaDecay6.root" "rootFiles/BpPythiaDecay6.root" "B^{+} #rightarrow c #bar{d} #bar{c} u"
./compareRootFiles "BpPythiaDecay7" "rootFiles/BpPythiaDecay7.root" "rootFiles/BpPythiaDecay7.root" "B^{+} #rightarrow u #bar{d} #bar{u} u (weak)"
./compareRootFiles "BpPythiaDecay8" "rootFiles/BpPythiaDecay8.root" "rootFiles/BpPythiaDecay8.root" "B^{+} #rightarrow c #bar{s} #bar{u} u (weak)"
./compareRootFiles "BpPythiaDecay9" "rootFiles/BpPythiaDecay9.root" "rootFiles/BpPythiaDecay9.root" "B^{+} #rightarrow u #bar{u} #bar{d} u (weak)"
./compareRootFiles "BpPythiaDecay10" "rootFiles/BpPythiaDecay10.root" "rootFiles/BpPythiaDecay10.root" "B^{+} #rightarrow d #bar{d} #bar{d} u (weak)"
./compareRootFiles "BpPythiaDecay11" "rootFiles/BpPythiaDecay11.root" "rootFiles/BpPythiaDecay11.root" "B^{+} #rightarrow s #bar{s} #bar{d} u (weak)"
./compareRootFiles "BpPythiaDecay12" "rootFiles/BpPythiaDecay12.root" "rootFiles/BpPythiaDecay12.root" "B^{+} #rightarrow u #bar{u} #bar{s} u (weak)"
./compareRootFiles "BpPythiaDecay13" "rootFiles/BpPythiaDecay13.root" "rootFiles/BpPythiaDecay13.root" "B^{+} #rightarrow d #bar{d} #bar{s} u (weak)"
./compareRootFiles "BpPythiaDecay14" "rootFiles/BpPythiaDecay14.root" "rootFiles/BpPythiaDecay14.root" "B^{+} #rightarrow s #bar{s} #bar{s} u (weak)"
./compareRootFiles "BpPythiaDecay15" "rootFiles/BpPythiaDecay15.root" "rootFiles/BpPythiaDecay15.root" "B^{+} #rightarrow #bar{s} u"
./compareRootFiles "BpPythiaDecay16" "rootFiles/BpPythiaDecay16.root" "rootFiles/BpPythiaDecay16.root" "B^{+} #rightarrow #bar{cs}_{1} uu_{1}"
