#!/bin/bash

# Find platform.
#
#check_platform () {

export ARCH="`uname`"

gcc_major=$(g++ --version | sed '2,$d;s/^[^ ]\+[ ]\+[^ ]\+[ ]\+\([0-9]\+\)\..*$/\1/')
gcc_minor=$(g++ --version | sed '2,$d;s/^.*GCC)[ ]\+[0-9]\+\.\([0-9]\+\)\.\([0-9]\+\).*$/\1\2/')

slc_major=""

#echo -n  "Checking for OS ... " >&2
if [ ! -s /etc/redhat-release ] ; then
   echo " not RedHat-derived. Stop." >&2
   exit 1
fi
system=Unknown
if [ "x$(grep "Scientific Linux" /etc/redhat-release)" = "x" ] ; then   
   system="`uname`"
#   echo "Red Hat Linux" >&2
else
   system=slc
   slc_major=$(sed 's/^.*[Rr]elease[ ]\+\([0-9]\+\)\..*$/\1/' < /etc/redhat-release)
#   echo "SLC "$slc_major >&2
fi

#echo -n "Checking for machine ... " >&2
machine=$(uname -m | grep -E "i[3456]86")
if [ "x$machine" = "x" ] ; then
	machine=$(uname -m)
	case "X${machine}" in 
		"Xx86_64") machine="amd64" ;; 
	esac
else
	machine="ia32"
fi
#echo $machine >&2

platform="${system}${slc_major}_${machine}_gcc${gcc_major}${gcc_minor}"
platform=$(echo ${platform} | sed 's/gcc34[0-9]*$/gcc34/')
platform=$(echo ${platform} | sed 's/gcc41[0-9]*$/gcc41/')
platform=$(echo ${platform} | sed 's/gcc42[0-9]*$/gcc42/')
platform=$(echo ${platform} | sed 's/gcc43[0-9]*$/gcc43/')
platform=$(echo ${platform} | sed 's/gcc44[0-9]*$/gcc44/')
platform=$(echo ${platform} | sed 's/gcc45[0-9]*$/gcc45/')

#echo "Platform is "${platform}
echo ${platform}
