#!/bin/sh
# parameters: $1 - generator, $2 - CVS tag
#
# computers for builds: lx64slc4, lx32slc4
# special AMD64 computer to build: lxbuild056
#

if [ "x$1" = "x" ]; then
 echo 'usage: installgen generatorname [tag]  (default tag is HEAD)'
 exit 1
fi
cvsflag=""
if [ ! "x$2" = "x" ]; then
 cvsflag="-r $2"
fi

if [ "x$MCGENERATORS" = "x" ]; then
  echo
  echo You have to define MCGENERATORS variable.
  echo you should define MCGENERATORS=/afs/cern.ch/sw/lcg/external/MCGenerators
  echo
  exit 1
fi
if [ "x$MCGREPLICA" = "x" ]; then
  echo
  echo You have to define MCGREPLICA variable.
  echo If you want to write your version into MCGENERATORS replica,
  echo you should define MCGREPLICA=/afs/.cern.ch/sw/lcg/external/MCGenerators
  echo
  exit 1
fi

workdir=`pwd`

mkdir -p createtar
cd createtar
rm -rf $1
mkdir $1
cd $1
cvs co $cvsflag simu/GENSER2/$1
if [ ! -d simu/GENSER2/$1 ]; then
  echo Checkout is not performed! CVSROOT is not defined or wrong tag or module name. Exiting.
  exit 1
fi
cp simu/GENSER2/$1/lcgscripts/mknewgenerator .
cp simu/GENSER2/$1/lcgscripts/build_install ../../.

./mknewgenerator --from_installgen

cd ${workdir}

#rm -fr createtar/ # We don't need to make the same job twice!

echo -e  "\n\nUse ./build_install to build $1\n"
#cd ..
#build_install
